import { Inter } from "next/font/google";
import "../globals.css";
import NavTop from "@/component/NavTop";
import NavBot from "@/component/NavBot";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <>
      <header>
        <NavTop />
        <NavBot />
      </header>
      <main className="py-[.4rem] px-[1.8rem]">{children}</main>
    </>
  );
}
