import { Inter } from "next/font/google";
import "./globals.css";
import NavTop from "@/component/NavTop";
import NavBot from "@/component/NavBot";

const inter = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <header>
          <NavTop />
          <NavBot />
        </header>
        <main className="py-[.4rem] px-[1.8rem]">{children}</main>
      </body>
    </html>
  );
}
